const mongoose = require("mongoose");

const correctionRequestSchema = new mongoose.Schema(
  {
    requestedBy: { type: String, trim: true, default: "" },
    requestedAt: { type: Date, default: Date.now },
    reason: { type: String, trim: true, default: "" },
    requestedStatus: {
      type: String,
      enum: [
        "PRESENT",
        "ABSENT",
        "LATE",
        "HALF_DAY",
        "ON_LEAVE",
        "HOLIDAY",
        "WEEKLY_OFF",
        "WORK_FROM_HOME",
        "MISSING_CHECKOUT",
      ],
      default: "PRESENT",
    },
    requestedCheckIn: { type: String, trim: true, default: "" },
    requestedCheckOut: { type: String, trim: true, default: "" },
    status: { type: String, enum: ["PENDING", "APPROVED", "REJECTED"], default: "PENDING" },
    reviewedBy: { type: String, trim: true, default: "" },
    reviewedAt: { type: Date, default: null },
    reviewerNote: { type: String, trim: true, default: "" },
  },
  { _id: true }
);

const attendanceSchema = new mongoose.Schema(
  {
    companyId: { type: mongoose.Schema.Types.ObjectId, ref: "Company", required: true, index: true },
    companyCode: { type: String, trim: true, default: "", index: true },
    employeeId: { type: String, trim: true, required: true, index: true },
    employeeName: { type: String, trim: true, default: "" },
    department: { type: String, trim: true, default: "" },
    date: { type: String, trim: true, required: true, index: true },
    status: {
      type: String,
      enum: [
        "PRESENT",
        "ABSENT",
        "LATE",
        "HALF_DAY",
        "ON_LEAVE",
        "HOLIDAY",
        "WEEKLY_OFF",
        "WORK_FROM_HOME",
        "MISSING_CHECKOUT",
      ],
      required: true,
    },
    checkIn: { type: String, trim: true, default: "" },
    checkOut: { type: String, trim: true, default: "" },
    shiftName: { type: String, trim: true, default: "" },
    workLocation: { type: String, trim: true, default: "" },
    mode: { type: String, trim: true, default: "MANUAL" },
    lateMinutes: { type: Number, default: 0 },
    earlyMinutes: { type: Number, default: 0 },
    workedHours: { type: Number, default: 0 },
    overtimeHours: { type: Number, default: 0 },
    autoGenerated: { type: Boolean, default: false },
    notes: { type: String, trim: true, default: "" },
    markedBy: { type: String, trim: true, default: "" },
    lockedForPayroll: { type: Boolean, default: false },
    lockedPayrollRunId: { type: mongoose.Schema.Types.ObjectId, ref: "PayrollRun", default: null },
    correctionRequests: { type: [correctionRequestSchema], default: [] },
  },
  { timestamps: true }
);

attendanceSchema.index({ companyId: 1, employeeId: 1, date: 1 }, { unique: true });
attendanceSchema.index({ companyId: 1, date: 1, status: 1 });

module.exports = mongoose.model("Attendance", attendanceSchema);
