const mongoose = require("mongoose");

const companyServiceAccessSchema = new mongoose.Schema(
  {
    companyId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Company",
      required: true,
      unique: true,
    },
    companyCode: { type: String, trim: true, default: "" },
    employees: [
      {
        id: { type: String, trim: true, required: true },
        employeeId: { type: String, trim: true, default: "" },
        companyCode: { type: String, trim: true, default: "" },
        name: { type: String, trim: true, required: true },
        role: { type: String, trim: true, default: "Employee" },
        department: { type: String, trim: true, default: "General" },
        type: { type: String, enum: ["EMPLOYEE"], default: "EMPLOYEE" },
        email: { type: String, trim: true, default: "" },
        phone: { type: String, trim: true, default: "" },
        contact: { type: String, trim: true, default: "" },
        username: { type: String, trim: true, lowercase: true, default: "" },
        photoUrl: { type: String, trim: true, default: "" },
        aadhaarNumber: { type: String, trim: true, default: "" },
        aadhaarStatus: { type: String, trim: true, default: "" },
        panNumber: { type: String, trim: true, default: "" },
        panStatus: { type: String, trim: true, default: "" },
        employmentType: { type: String, trim: true, default: "" },
        joiningDate: { type: String, trim: true, default: "" },
        manager: { type: String, trim: true, default: "" },
        supervisorName: { type: String, trim: true, default: "" },
        workLocation: { type: String, trim: true, default: "" },
        shiftName: { type: String, trim: true, default: "" },
        shiftStart: { type: String, trim: true, default: "" },
        shiftEnd: { type: String, trim: true, default: "" },
        weeklyOff: { type: String, trim: true, default: "" },
        attendanceMode: { type: String, trim: true, default: "" },
        geoTaggingEnabled: { type: Boolean, default: false },
        accessLevel: { type: String, trim: true, default: "" },
        dateOfBirth: { type: String, trim: true, default: "" },
        dob: { type: String, trim: true, default: "" },
        gender: { type: String, trim: true, default: "" },
        address: { type: String, trim: true, default: "" },
        emergencyContactName: { type: String, trim: true, default: "" },
        emergencyContactPhone: { type: String, trim: true, default: "" },
        notes: { type: String, trim: true, default: "" },
        hasLogin: { type: Boolean, default: false },
        loginUpdatedAt: { type: Date, default: null },
        passwordUpdatedAt: { type: Date, default: null },
        status: { type: String, enum: ["ACTIVE", "INACTIVE"], default: "ACTIVE" },
        assignedHrId: { type: String, trim: true, default: "" },
        assignedHrName: { type: String, trim: true, default: "" },
        assignedAt: { type: Date, default: null },
      },
    ],
    hrAccounts: [
      {
        id: { type: String, trim: true, required: true },
        companyCode: { type: String, trim: true, default: "" },
        name: { type: String, trim: true, required: true },
        role: { type: String, trim: true, default: "HR" },
        department: { type: String, trim: true, default: "Human Resources" },
        designation: { type: String, trim: true, default: "HR" },
        email: { type: String, trim: true, default: "" },
        phone: { type: String, trim: true, default: "" },
        contact: { type: String, trim: true, default: "" },
        status: { type: String, enum: ["ACTIVE", "INACTIVE"], default: "ACTIVE" },
        notes: { type: String, trim: true, default: "" },
        username: { type: String, trim: true, lowercase: true, default: "" },
        userId: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
        hasLogin: { type: Boolean, default: false },
        loginUpdatedAt: { type: Date, default: null },
        passwordUpdatedAt: { type: Date, default: null },
      },
    ],
    attendancePolicy: {
      graceMinutes: { type: Number, default: 10 },
      halfDayMaxHours: { type: Number, default: 4.5 },
      fullDayHours: { type: Number, default: 8 },
      overtimeAfterHours: { type: Number, default: 9 },
      weeklyOffDays: { type: [String], default: ["Sunday"] },
      autoAbsentEnabled: { type: Boolean, default: true },
      autoAbsentHour: { type: Number, default: 1 },
    },
    subscription: {
      planKey: { type: String, trim: true, default: "STARTER" },
      billing: { type: String, enum: ["MONTHLY", "YEARLY"], default: "MONTHLY" },
      purchasedAt: { type: Date, default: Date.now },
      expiresAt: { type: Date, default: null },
      purchaseCount: { type: Number, default: 1 },
      renewCount: { type: Number, default: 0 },
      history: [
        {
          planKey: { type: String, trim: true, default: "STARTER" },
          billing: { type: String, enum: ["MONTHLY", "YEARLY"], default: "MONTHLY" },
          purchasedAt: { type: Date, default: Date.now },
          expiresAt: { type: Date, default: null },
        },
      ],
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model("CompanyServiceAccess", companyServiceAccessSchema);
